Revert "surya: Nuke framework compatibility matrix"
checkvintf I 06-26 22:50:59 462246 462246 check_vintf.cpp:84] List '/home/windeqk/nezukoos-1.4/out/target/product/surya/obj/PACKAGING/target_files_intermediates/nezuko_surya-target_files-eng
.windeqk/PRODUCT/etc/vintf/': No such file or directory
checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554] files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:

checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554]     com.fingerprints.extension@1.0::IFingerprintEngineering/default
checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554]     com.fingerprints.extension@1.0::IFingerprintNavigation/default
checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554]     com.fingerprints.extension@1.0::IFingerprintSensorTest/default
checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554]     vendor.lineage.power.IPower/default
checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554] Suggested fix:
checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554] 1. Update deprecated HALs to the latest version.
checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554] 2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 4.
checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554] 3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 4 where applicable.
checkvintf E 06-26 22:50:59 462246 462246 check_vintf.cpp:554] 4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Su
ccess

Compressing system.new.dat with brotli
Compressing vendor.new.dat with brotli
Compressing product.new.dat with brotli
Compressing system_ext.new.dat with brotli
Traceback (most recent call last):
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 72, in _run_code
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/__main__.py", line 12, in <module>
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 174, in _run_module_as_main
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/internal/stdlib/runpy.py", line 72, in _run_code
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2336, in <module>
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2315, in main
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 2055, in GenerateNonAbOtaPackage
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 898, in WriteFullOTAPackage
  File "/home/windeqk/nezukoos-1.4/out/host/linux-x86/bin/ota_from_target_files/ota_from_target_files.py", line 630, in CheckVintfIfTrebleEnabled
RuntimeError: VINTF compatibility check failed

This reverts commit 6b7e2ff5cd06db954f8465cb517ab04cf828cb96.

Signed-off-by: windeqk <71609034+windeqk@users.noreply.github.com>